# Generated by Django 2.2.10 on 2021-06-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timcheh', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
